<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <!-- AOT flags -->
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TrimMode>full</TrimMode>
    <PublishTrimmed>true</PublishTrimmed>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XDown.Core\XDown.Core.csproj" />
  </ItemGroup>

</Project>
